/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawalsRouteImport } from './routes/withdrawals'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SupportRouteImport } from './routes/support'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as IndexRouteImport } from './routes/index'

const WithdrawalsRoute = WithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fees': typeof FeesRoute
  '/login': typeof LoginRoute
  '/support': typeof SupportRoute
  '/transactions': typeof TransactionsRoute
  '/withdrawals': typeof WithdrawalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fees': typeof FeesRoute
  '/login': typeof LoginRoute
  '/support': typeof SupportRoute
  '/transactions': typeof TransactionsRoute
  '/withdrawals': typeof WithdrawalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fees': typeof FeesRoute
  '/login': typeof LoginRoute
  '/support': typeof SupportRoute
  '/transactions': typeof TransactionsRoute
  '/withdrawals': typeof WithdrawalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fees'
    | '/login'
    | '/support'
    | '/transactions'
    | '/withdrawals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fees'
    | '/login'
    | '/support'
    | '/transactions'
    | '/withdrawals'
  id:
    | '__root__'
    | '/'
    | '/fees'
    | '/login'
    | '/support'
    | '/transactions'
    | '/withdrawals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeesRoute: typeof FeesRoute
  LoginRoute: typeof LoginRoute
  SupportRoute: typeof SupportRoute
  TransactionsRoute: typeof TransactionsRoute
  WithdrawalsRoute: typeof WithdrawalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdrawals': {
      id: '/withdrawals'
      path: '/withdrawals'
      fullPath: '/withdrawals'
      preLoaderRoute: typeof WithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeesRoute: FeesRoute,
  LoginRoute: LoginRoute,
  SupportRoute: SupportRoute,
  TransactionsRoute: TransactionsRoute,
  WithdrawalsRoute: WithdrawalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
